export {
  addAnalystFinding,
  addAnalystHypothesis,
  addAnalystTask,
  buildCaseDecisionRecords,
  buildCaseEvidenceRecords,
  buildIncidentCaseReport,
  collectAnalystEvidence,
  compileScenarioDefinition,
  createAnalystCaseState,
  edrProjection,
  executeSyntheticHostCommand,
  finalizeScenarioState,
  getEdrEndpointInvestigation,
  getIdentityAccountInvestigation,
  getIdentityInventory,
  getObservedEdrDeviceIds,
  getScenarioState,
  identityProjection,
  rebuildProjection,
  replaySyntheticHostCommands,
  resolveCollectedEvidence,
  searchSiem,
  setAnalystCasePhase,
  siemProjection,
  updateAnalystHypothesisStatus,
  updateAnalystTaskStatus,
} from "@polymorph/simulation";

export type {
  AnalystCasePhase,
  AnalystCaseState,
  AnalystHypothesisStatus,
  AnalystTaskStatus,
  CaseDecisionRecord,
  CaseEvidenceRecord,
  EdrEndpointInvestigation,
  EdrProcessTreeNode,
  EdrProjectionState,
  IdentityAccountInvestigation,
  IdentityInventoryEntry,
  IdentityProjectionState,
  IncidentCaseReport,
  ScenarioAction,
  ScenarioDefinition,
  ScenarioOutcome,
  ScenarioOutcomeStatus,
  ScenarioScore,
  ScenarioState,
  SiemEventRecord,
  SiemSearchRequest,
  SiemSearchResult,
  SimulationEvent,
  SyntheticHostCommand,
  SyntheticHostCommandExecution,
  SyntheticHostCommandInvocation,
  SyntheticHostState,
} from "@polymorph/simulation";
