export {
  addAnalystFinding,
  collectAnalystEvidence,
  compileScenarioDefinition,
  createAnalystCaseState,
  edrProjection,
  finalizeScenarioState,
  getEdrEndpointInvestigation,
  getIdentityAccountInvestigation,
  getIdentityInventory,
  getObservedEdrDeviceIds,
  getScenarioState,
  identityProjection,
  rebuildProjection,
  resolveCollectedEvidence,
  searchSiem,
  siemProjection,
} from "@polymorph/simulation";

export type {
  EdrEndpointInvestigation,
  EdrProcessTreeNode,
  EdrProjectionState,
  IdentityAccountInvestigation,
  IdentityInventoryEntry,
  IdentityProjectionState,
  ScenarioAction,
  ScenarioDefinition,
  ScenarioOutcomeStatus,
  ScenarioScore,
  ScenarioState,
  SiemEventRecord,
  SiemSearchRequest,
  SiemSearchResult,
} from "@polymorph/simulation";
